### PR TITLE
Generate OpenAPI schema and place it into docs folder using GH Actions

### LINKED ISSUE #2: OpenAPI schema to be generated and placed into docs automatically after each push to master, generated through GitHub Actions.
exactly what the title says. won't do it right now. easy to approach for a DevOps beginner.

Probably have a `doc` file there which gets automated and a redoc + sphinx service (deployed it here: https://urnode.readthedocs.io/) is automatically deployed off of. The why's and hows can be debated!

### PR DESCRIPTION
**Pull request by RoguedBear**
i've made the workflow file that'll generate the openAPI schema using the django cli and then place it into the docs directory and commit it.

I've tested this workflow in [`test-schema-ghaction` branch](https://github.com/RoguedBear/urNode/tree/test-schema-ghaction) in my fork.

Ideally this workflow will trigger when there's a push to main/master branch and on pull request branches that open towards main/master branch

--- 

closes #2 (i think? im not sure if the doc part is complete, will redoc automatically build and add this inside the sphinx docs now, as it happens with the IntelOwl docs?)

### CODE REVIEW

**Comment by RoguedBear** [comment]
ok, interesting the action tripped up on pushing to a fork's branch. 
let me work on this

**Comment by RoguedBear** [comment]
I've made 2 new changes now:
- apart from branch triggers, workflow triggers when files inside `urNode-backend/**` have been changed
- a fix for the action not able to push on fork's branches have been made taking help from [here](https://github.com/stefanzweifel/git-auto-commit-action/#workflow-should-run-in-base-repository) but that can be tested by opening a dummy PR here to trigger that workflow. 
If it doesn't work even then, then I'll remove the PR as a trigger altogether and have it work only on pushes to main/master branch where i know for sure and have tested that this'll work :)))

**Comment by 0x0elliot** [comment]
thanks for your contribution!

**Comment by RoguedBear** [comment]
yayay!
i am glad i could help

**Pull request merged**
